metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true


metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    #- image
    - memory
    - network
  hosts: ['unix:///var/run/docker.sock']
  period: 10s
  enabled: true

# Module: rabbitmq
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-rabbitmq.html

- module: rabbitmq
  metricsets: ["node", "queue", "connection"]
  enabled: true
  period: 10s
  hosts: "rabbitmq:15672"
  username: guest
  password: guest

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["https://${ELASTICSEARCH_HOST_PORT}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.verification_mode: none

setup.kibana:
  host: "https://${KIBANA_HOST_PORT}"
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.verification_mode: none

setup.dashboards.always_kibana: true
setup.dashboards.retry.enabled: true
setup.dashboards.enabled: true

http.enabled: true
http.host: 0.0.0.0