output.elasticsearch:
  # Array of hosts to connect to.
  hosts: [ "https://${ELASTICSEARCH_HOST_PORT}" ]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.verification_mode: none


setup.kibana:
  host: "https://${KIBANA_HOST_PORT}"
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.verification_mode: none

